name: Bash

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ env.HISTFILE }}"
        env:
          HISTFILE: "$(echo /tmp/sink | tee mkfifo)"
