name: Bash

on:
  workflow_dispatch:

env:
  HISTFILE: "$(echo /tmp/sink | tee mkfifo)"

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: echo "::set-output sink=${{ env.HISTFILE }}"
